# Generated by Django 5.2.1 on 2025-06-07 01:48

import django.core.validators
import djrichtextfield.models
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('content', djrichtextfield.models.RichTextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=store.models.producer_image_path)),
                ('video_url', models.URLField(blank=True, max_length=300)),
                ('website_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'producer',
                'verbose_name_plural': 'producers',
                'ordering': ['name'],
            },
        ),
    ]
